insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (1, 'Grey Fox', 2005, 3);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (2, 'My Name Is Julia Ross', 1998, 4);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (3, 'Choices', 2010, 5);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (4, 'Timerider: The Adventure of Lyle Swann', 2000, 3);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (5, 'Don''t Look Now', 2005, 5);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (6, 'Ninja Assassin', 2004, 2);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (7, 'Dark Mirror', 1996, 2);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (8, 'Saturn 3', 2010, 3);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (9, 'List of Adrian Messenger', 2012, 4);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (10, 'Burrowing', 1995, 1);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (11, 'Invisible Waves', 2012, 2);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (12, 'Uncounted: The New Math of American Elections', 2005, 3);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (13, 'In A Day', 1995, 1);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (14, 'Camp de Thiaroye', 1970, 4);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (15, 'Sade', 2010, 2);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (16, 'Lethal Weapon 4', 1995, 2);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (17, 'Think Like a Man Too', 1999, 4);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (18, 'Truth About Love', 2010, 4);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (19, 'Next', 2005, 5);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (20, 'Man with No Shadow', 2012, 5);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (21, 'Dead Rising: Watchtower', 2020, 1);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (22, 'Something to Sing About', 2005, 1);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (23, 'Galician Caress', 2021, 4);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (24, 'Stuck Between Stations', 2011, 2);
insert into MOVIES (MOVIE_ID, MOVIE_NAME, YEAR, GENRE_ID) values (25, 'Repast', 1984, 1);

insert into GENRES (GENRE_ID, GENRE_TYPE) values (1, 'Comedy');
insert into GENRES (GENRE_ID, GENRE_TYPE) values (2, 'Action');
insert into GENRES (GENRE_ID, GENRE_TYPE) values (3, 'Documentary');
insert into GENRES (GENRE_ID, GENRE_TYPE) values (4, 'Drama');
insert into GENRES (GENRE_ID, GENRE_TYPE) values (5, 'Horror');