CREATE TABLE GENRES(
  GENRE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  GENRE_TYPE VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE MOVIES(
  MOVIE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  MOVIE_NAME VARCHAR(64) NOT NULL,
  YEAR INTEGER NOT NULL,
  GENRE_ID BIGINT NOT NULL
);

ALTER TABLE MOVIES ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID);

